# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-02 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170331_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='course',
        ),
    ]
