# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_userfavorite_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.BigIntegerField(verbose_name='\u624b\u673a'),
        ),
    ]
