# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20170406_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a'),
        ),
    ]
